micronaut:
  application:
    name: micronautTest
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/test-db
    driverClassName: org.postgresql.Driver
    username: test-user
    password: test-user
    dialect: POSTGRES

#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    dialect: H2

#    schema-generate: CREATE_DROP
